#!/usr/bin/env python3
"""Generate Python/C++/docs agent-protocol artifacts from
agent_protocol_abi.yaml (SSOT for the AgentAxiDriver SQ/CQ protocol,
spec section 8)."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import yaml

SCALAR_FORMATS = {"u8": "B", "u16": "H", "u32": "I", "u64": "Q"}
SCALAR_BYTES = {"u8": 1, "u16": 2, "u32": 4, "u64": 8}
VECTOR_TYPES = {"bytes32": 32}
CPP_TYPES = {"u8": "uint8_t", "u16": "uint16_t", "u32": "uint32_t", "u64": "uint64_t"}


def cpp_name(record_name: str) -> str:
    return "".join(part.capitalize() for part in record_name.split("_"))


def check_layout(name, fields, total):
    cursor = 0
    seen = set()
    for field in fields:
        ftype = field["type"]
        size = SCALAR_BYTES.get(ftype, VECTOR_TYPES.get(ftype))
        assert size, f"unknown type {ftype}"
        assert field["name"] not in seen
        seen.add(field["name"])
        assert field["offset"] == cursor, f"{name}.{field['name']} gap/order"
        cursor = field["offset"] + size
        assert cursor <= total
    assert cursor == total, f"{name} covers {cursor} != {total}"


def load_schema(path: Path) -> dict:
    schema = yaml.safe_load(path.read_bytes())
    for record in schema["records"].values():
        check_layout(record.get("name", ""), record["fields"], record["bytes"]) \
            if False else check_layout("", record["fields"], record["bytes"])
    return schema


def sha_of(schema, yaml_bytes: bytes) -> str:
    return hashlib.sha256(yaml_bytes).hexdigest()


def render_python(schema, sha):
    lines = [
        '"""Generated by generate_agent_abi.py -- do not edit.',
        "",
        f"schema_sha256: {sha}",
        '"""',
        "",
        "import struct",
        "",
        "",
        f"SCHEMA_SHA256 = {sha!r}",
        f"ABI_MAJOR = {schema['abi']['major']}",
        f"ABI_MINOR = {schema['abi']['minor']}",
        "",
    ]
    for enum_name, values in schema["enums"].items():
        lines.append(f"class {enum_name.upper()}:")
        for key, value in values.items():
            lines.append(f"    {key} = {value}")
        lines.append("")
    lines.append("DETAIL_CODE = {")
    for key, value in schema["detail_code_registry"].items():
        lines.append(f"    {key!r}: {value},")
    lines.append("}")
    lines.append("DETAIL_CODE_BY_VALUE = {v: k for k, v in DETAIL_CODE.items()}")
    lines.append("")
    for record_name, record in schema["records"].items():
        fmt = "".join(
            SCALAR_FORMATS[f["type"]] if f["type"] in SCALAR_FORMATS
            else f"{VECTOR_TYPES[f['type']]}s"
            for f in record["fields"]
        )
        lines.append(f"{record_name}_BYTES = {record['bytes']}")
        lines.append(f"{record_name}_FORMAT = struct.Struct('<{fmt}')")
        lines.append(f"{record_name}_FIELDS = {record['fields']!r}")
        lines.append(f"{record_name}_FIELD_OFFSETS = " + "{"
            + ", ".join(f"{f['name']!r}: {f['offset']}" for f in record["fields"]) + "}")
        crc = record.get("crc")
        if crc:
            lines.append(f"{record_name}_CRC_COVER = {crc.get('cover')!r}")
            lines.append(f"{record_name}_CRC_FIELD = {crc['field']!r}")
        lines.append("")
    return "\n".join(lines) + "\n"


def render_cpp(schema, sha):
    out = [
        "// Generated by util/mesh_ir/mesh_ir/abi/generate_agent_abi.py -- do not edit.",
        f"// schema_sha256: {sha}",
        "#ifndef GEM5_DEV_AI_MESH_GENERATED_AGENT_PROTOCOL_ABI_HH",
        "#define GEM5_DEV_AI_MESH_GENERATED_AGENT_PROTOCOL_ABI_HH",
        "",
        "#include <array>",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "namespace gem5",
        "{",
        "namespace ai_mesh",
        "{",
        "namespace agent_abi",
        "{",
        "",
        f"constexpr uint16_t kAbiMajor = {schema['abi']['major']};",
        f"constexpr uint16_t kAbiMinor = {schema['abi']['minor']};",
        "",
    ]
    for enum_name, values in schema["enums"].items():
        pascal = "".join(part.capitalize() for part in enum_name.split("_"))
        out.append(f"enum class {pascal} : uint16_t")
        out.append("{")
        for key, value in values.items():
            out.append(f"    {key} = {value:#06x},")
        out.append("};")
        out.append("")
        for key, value in values.items():
            out.append(f"constexpr uint16_t k{pascal}{key} = {value:#06x};")
        out.append("")
    out.append("// DetailCode closed registry (V1)")
    out.append("enum DetailCode : uint32_t")
    out.append("{")
    for key, value in schema["detail_code_registry"].items():
        out.append(f"    {key} = {value:#010x},")
    out.append("};")
    out.append("")
    for record_name, record in schema["records"].items():
        struct = cpp_name(record_name)
        out.append(f"struct {struct}")
        out.append("{")
        for field in record["fields"]:
            ftype = field["type"]
            if ftype in CPP_TYPES:
                out.append(f"    {CPP_TYPES[ftype]} {field['name']} = 0;")
            elif ftype == "bytes32":
                out.append(f"    std::array<uint8_t, 32> {field['name']} = {{}};")
        out.append("};")
        out.append(f"constexpr uint32_t k{struct}Bytes = {record['bytes']};")
        for field in record["fields"]:
            fname = "k" + struct + "".join(
                part.capitalize() for part in field["name"].split("_"))
            out.append(f"constexpr uint32_t {fname}Offset = {field['offset']};")
        crc = record.get("crc")
        if crc:
            cover = crc.get("cover")
            if cover:
                out.append(f"constexpr uint32_t k{struct}CrcCoverBytes = {cover[1] - cover[0]};")
            else:
                out.append(f"constexpr uint32_t k{struct}CrcCoverBytes = 0; // field-zero variant")
            out.append(f"constexpr uint32_t k{struct}CrcFieldOffset = {record['bytes'] and [f['offset'] for f in record['fields'] if f['name'] == crc['field']][0]};")
        out.append("")
    out.extend([
        "inline uint8_t rdU8(const uint8_t *p) { return p[0]; }",
        "inline uint16_t rdU16(const uint8_t *p)",
        "{ return uint16_t(p[0]) | (uint16_t(p[1]) << 8); }",
        "inline uint32_t rdU32(const uint8_t *p)",
        "{ return uint32_t(rdU16(p)) | (uint32_t(rdU16(p + 2)) << 16); }",
        "inline uint64_t rdU64(const uint8_t *p)",
        "{ return uint64_t(rdU32(p)) | (uint64_t(rdU32(p + 4)) << 32); }",
        "",
        "uint32_t crc32c(const uint8_t *data, size_t size);",
        "",
        "} // namespace agent_abi",
        "} // namespace ai_mesh",
        "} // namespace gem5",
        "",
        "#endif // GEM5_DEV_AI_MESH_GENERATED_AGENT_PROTOCOL_ABI_HH",
        "",
    ])
    return "\n".join(out)


def render_markdown(schema, sha):
    out = [
        "# Agent Protocol ABI Reference",
        "",
        "Generated from `util/mesh_ir/mesh_ir/abi/agent_protocol_abi.yaml` -- do not edit.",
        "",
        f"- schema_sha256: `{sha}`",
        f"- ABI: {schema['abi']['major']}.{schema['abi']['minor']}",
        "",
        "## Enums",
        "",
    ]
    for name, values in schema["enums"].items():
        out.append(f"- `{name}`: " + ", ".join(f"{k}={v:#x}" for k, v in values.items()))
    out.append("")
    out.append("## Detail codes")
    out.append("")
    for key, value in schema["detail_code_registry"].items():
        out.append(f"- `{key}` = {value:#010x}")
    out.append("")
    out.append("## Records")
    out.append("")
    for name, record in schema["records"].items():
        out.append(f"### {name} ({record['bytes']} B)")
        out.append("")
        out.append("| field | type | offset |")
        out.append("|---|---|---:|")
        for field in record["fields"]:
            out.append(f"| `{field['name']}` | {field['type']} | {field['offset']} |")
        out.append("")
    return "\n".join(out) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--yaml", default=str(Path(__file__).with_name("agent_protocol_abi.yaml")))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    yaml_path = Path(args.yaml)
    repo = yaml_path.parents[4]
    outputs = {
        repo / "util/mesh_ir/mesh_ir/generated/agent_abi.py": None,
        repo / "src/dev/ai_mesh/generated/agent_protocol_abi.hh": None,
        repo / "docs/generated/agent_protocol_abi.md": None,
    }
    yaml_bytes = yaml_path.read_bytes()
    schema = load_schema(yaml_path)
    sha = sha_of(schema, yaml_bytes)
    rendered = {
        repo / "util/mesh_ir/mesh_ir/generated/agent_abi.py": render_python(schema, sha),
        repo / "src/dev/ai_mesh/generated/agent_protocol_abi.hh": render_cpp(schema, sha),
        repo / "docs/generated/agent_protocol_abi.md": render_markdown(schema, sha),
    }
    stale = []
    for path, content in rendered.items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            print(f"wrote {path}")
    if args.check and stale:
        print("stale generated files: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
