# -*- mode:python -*-

Import('*')

# Keep the AXI endpoint, helpers, and tests completely out of all legacy Ruby
# and ISA builds.
if env['CONF']['PROTOCOL'] != 'AXI_MESH':
    Return()

SimObject('AxiGarnetEndpoint.py', sim_objects=[
    'AxiInitiatorAdapter',
    'AxiTargetAdapter',
])
SimObject('AxiTraceTester.py', sim_objects=['AxiTraceTester'])

Source('axi_garnet_endpoint.cc')
Source('axi_determinism.cc')
Source('axi_packetization.cc')
Source('axi_validation.cc')
Source('axi_protocol_checker.cc')
Source('axi_initiator_adapter.cc')
Source('axi_target_adapter.cc')
Source('synthetic_hbm_backend.cc')
Source('axi_trace_tester.cc')
DebugFlag('AxiGarnetProbe')

GTest('axi_packetization.test',
      'axi_packetization.test.cc', 'axi_packetization.cc')
GTest('axi_validation.test',
      'axi_validation.test.cc', 'axi_validation.cc')
GTest('axi_write_pairing.test',
      'axi_write_pairing.test.cc',
      'axi_initiator_adapter.cc', 'axi_target_adapter.cc',
      'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('axi_ordering.test',
      'axi_ordering.test.cc',
      'axi_initiator_adapter.cc', 'axi_target_adapter.cc',
      'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('axi_flow_control.test',
      'axi_flow_control.test.cc',
      'axi_initiator_adapter.cc', 'axi_target_adapter.cc',
      'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('axi_error_response.test',
      'axi_error_response.test.cc',
      'axi_target_adapter.cc', 'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('synthetic_hbm_backend.test',
      'synthetic_hbm_backend.test.cc',
      'axi_target_adapter.cc', 'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('axi_simple_memory.test',
      'axi_simple_memory.test.cc',
      'axi_target_adapter.cc', 'axi_validation.cc', 'synthetic_hbm_backend.cc')
GTest('axi_protocol_checker.test',
      'axi_protocol_checker.test.cc', 'axi_protocol_checker.cc',
      'axi_determinism.cc')
