# -*- mode:python -*-

Import("*")


SimObject('Cache2ChiBridge.py',sim_objects=['Cache2ChiBridge'])
SimObject('Chi2ClassicMemBridge.py',sim_objects=['Chi2ClassicMemBridge'])
SimObject('ChiFlitSink.py',sim_objects=['ChiFlitSink'])
SimObject('ChiRouterRefModel.py',sim_objects=['ChiRouterRefModel'])

# Base CHI component + a concrete node
SimObject('base/BasicChiComponent.py', sim_objects=['BasicChiComponent'])
SimObject('HomeNodeFull.py', sim_objects=['HomeNodeFull'])


Source('Cache2ChiBridge.cc')
Source('Chi2ClassicMemBridge.cc')
Source('ChiFlitSink.cc')
Source('ChiRouterRefModel.cc')
Source('base/BasicChiComponent.cc')

Source('HomeNodeFull.cc')
Source('HomeLinkLayer.cc')
Source('HnfCoherencyController.cc')
Source('HnfPOCQStateGraph.cc')
Source('HnfSeqPOCQStateGraph.cc')
Source('HnfSLCSF.cc')
Source('HnfSLCSFBackend.cc')

GTest('hnf_pocq_state_graph.test',
      'HnfPOCQStateGraph.test.cc',
      'HnfPOCQStateGraph.cc')

GTest('hnf_seq_pocq_state_graph.test',
      'HnfSeqPOCQStateGraph.test.cc',
      'HnfSeqPOCQStateGraph.cc')

GTest('hnf_cc_types.test', 'HnfCcTypes.test.cc')

GTest('hnf_slcsf.test',
      'HnfSLCSF.test.cc',
      'HnfSLCSF.cc',
      'HnfSLCSFBackend.cc',
      with_tag('gem5 trace'))

GTest('hnf_slcsf_backend.test',
      'HnfSLCSFBackend.test.cc',
      'HnfSLCSF.cc',
      'HnfSLCSFBackend.cc',
      with_tag('gem5 trace'))

GTest('hnf_coherency_controller.test',
      'HnfCoherencyController.test.cc',
      'HnfCoherencyController.cc',
      'HnfPOCQStateGraph.cc',
      'HnfSeqPOCQStateGraph.cc',
      'HnfSLCSF.cc',
      'HnfSLCSFBackend.cc',
      with_tag('gem5 trace'))

GTest('cache2chi_bridge.test',
      'Cache2ChiBridge.test.cc',
      with_tag('gem5 trace'))

GTest('chi2classic_mem_bridge.test',
      'Chi2ClassicMemBridge.test.cc')

DebugFlag('Cache2ChiBridge')
DebugFlag('Chi2ClassicMemBridge')
DebugFlag('ChiFlitSink')
DebugFlag('ChiRouterRefModel')
DebugFlag('BasicChiComponent')
DebugFlag('HomeNodeFull')
DebugFlag('HomeLinkLayer')
DebugFlag('HnfCC')
DebugFlag('HnfSLCSF')
